### ISSUE TITLE
Does not work in flex containers...

### ISSUE THREAD

**Issue by douglasg14b** [JayeshLab/vue-resize-text#3]
If I have text in a flex container child, even if the container is set to grow, the text is set to the largest size even if it doesn't fit in the container, it is never made smaller.

**Comment by douglasg14b** [comment]
Not sure if it has to do with flex at all. Even if I explicitly set the element to a specific width in pixels, this still only maxes out the font size.

**Comment by douglasg14b** [comment]
Oh, this only resizes based on the element size, regardless of what's inside of it... I see.

**Comment by SobhanKhan** [comment]
Baby i have the same problem , how can I fix it?
